import Head from 'next/head'
import Hero from '@/components/Hero'
import NavBar from '@/components/NavBar';
import About from '@/components/About';
import Skills from '@/components/Skills';
import Experience from '@/components/Experience';
import Showcase from '@/components/Showcase';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" items-center">
      <NavBar />
      <Hero />         
      <About />
    <Skills />
    <Showcase />
    <Experience />

      </main>
    </>
  )
}
